name: build-mod
description: Builds the DS3 mod.

runs:
  using: composite

  steps:
  - uses: microsoft/setup-msbuild@v2
    with: {msbuild-architecture: x64}
  - run: msbuild --version
    shell: pwsh
 
  # From https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-actions-cache
  - name: Export GitHub Actions cache environment variables
    uses: actions/github-script@v7
    with:
      script: |
        core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
        core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

  - run: vcpkg integrate install
    working-directory: archipelago-client
    shell: pwsh
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  - run: vcpkg install
    working-directory: archipelago-client
    shell: pwsh
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  - name: Build mod
    run: msbuild archipelago-client\archipelago-client.vcxproj -verbosity:diag '-property:Configuration=Release;Platform=x64'
    shell: pwsh
    env:
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
